### ISSUE TITLE
使用-cachedir参数后，cache size和number of files都显示N/A，无法正常显示数值。

### ISSUE THREAD

**Issue by rayblade** [soulteary/apt-proxy#15]
使用-cachedir参数后，cache size和number of files都显示N/A，无法正常显示数值。

**Comment by zkc226** [comment]
代码里面写死了统计路径是 ./.aptcache，真机环境下可以通过软链接指向目标目录解决，容器环境下可以通过volume挂载解决：
```
services:
  apt-proxy:
    image: soulteary/apt-proxy:v0.5.3
    container_name: apt-proxy
    hostname: apt-proxy
    command:
      - --mode=all
      - --port=80
      - --ubuntu=cn:aliyun
      - --debian=cn:aliyun
      - --alpine=cn:aliyun
      - --centos=cn:aliyun
      - --cachedir=/.aptcache
    volumes:
      - ./var/aptcache:/.aptcache:rw
```
