### ISSUE TITLE
[feature request] suppott arch linux similar to pacoloco

### ISSUE THREAD

**Issue by tracure1337** [soulteary/apt-proxy#17]
[feature request] suppott arch linux similar to pacoloco

Thanks for your consideration.

**Comment by soulteary** [comment]
This is a valid distribution-support request and will remain open as an enhancement.

Acceptance should include a dedicated Arch/pacman distribution descriptor, repository URL and mirror-selection rules, correct caching for database/signature/package files, client configuration documentation, and end-to-end tests. It should not be implemented as an unrestricted upstream proxy.

**Comment by soulteary** [comment]
Sorry for the long silence on this one. As of v0.16.0 you can cache Arch repositories through `distributions.yaml`, without any code change. I verified the routing against the pacman layout (`.db`, `.db.sig`, `.files`, `.pkg.tar.zst`, `lastupdate` all resolve correctly):

 ```yaml
 distributions:
   - id: archlinux
     name: Arch Linux
     type: 10
     url_pattern: "/archlinux/(.+)$"
     benchmark_url: "lastupdate"
     cache_rules:
       - pattern: "\\.pkg\\.tar\\.(zst|xz)$"
         cache_control: "max-age=100000"
         rewrite: true
       - pattern: "\\.(db|files)(\\.sig|\\.tar\\.gz)?$"
         cache_control: "max-age=300"
         rewrite: true
       - pattern: ".*"
         cache_control: "max-age=300"
         rewrite: true
     mirrors:
       official:
         - "mirrors.tuna.tsinghua.edu.cn/archlinux/"
 ```

 `/etc/pacman.d/mirrorlist`:

 ```text
 Server = http://<apt-proxy host>:3142/archlinux/$repo/os/$arch
 ```

 Run with `--distributions-config=<path>` (the server does not probe for the file) and `--mode=all` (the default).

 **To set expectations:** this is generic HTTP caching, not a pacoloco equivalent. There is no db-aware invalidation, no prefetch and no Arch-specific logic — package files are cached long, the `.db` files briefly. For most "several Arch boxes on one LAN" setups that is enough; if you need pacoloco's repo awareness, it is still the better tool.
