### ISSUE TITLE
如果需要为deepin提供代理缓存,应该如何配置?

### ISSUE THREAD

**Issue by liuxia19872003** [soulteary/apt-proxy#23]
如果需要为国产的linux deepin提供代理缓存,应该如何配置?

**Comment by soulteary** [comment]
这个使用场景合理，但 Deepin 不能仅因为基于 Debian 就直接视为完整兼容：它有独立的仓库域名、路径和发布结构。

当前版本已经支持通过 `distributions.yaml` 维护发行版匹配规则与镜像列表。本 Issue 将按发行版增强需求保留，后续需要补一份经过实际 `apt update/install` 验证的 Deepin 配置示例；如果要求 Debian 与 Deepin 在同一实例中同时工作，还需要确认当前发行版类型和路由不会互相覆盖。

**Comment by soulteary** [comment]
v0.17.0 起仓库内提供了一份现成的示例：[`examples/custom-distros/`](https://github.com/soulteary/apt-proxy/tree/main/examples/custom-distros)，其中就包含 Deepin。 @liuxia19872003 

Deepin 用 `type: 6`（内置类型是 1–5，填其它正整数即注册一个新发行版，拥有自己的镜像列表、测速和 rewriter）：

```yaml
distributions:
  - id: deepin
    name: Deepin
    type: 6
    url_pattern: "/deepin/(.+)$"
    benchmark_url: "dists/apricot/main/binary-amd64/Release"
    cache_rules:
      - pattern: "deb$"
        cache_control: "max-age=100000"
        rewrite: true
      - pattern: "(InRelease|Release(\\.gpg)?)$"
        cache_control: "max-age=3600"
        rewrite: true
      - pattern: ".*"          # 必须有兜底规则
        cache_control: "max-age=3600"
        rewrite: true
    mirrors:
      official:
        - "community-packages.deepin.com/deepin/"
        - "mirrors.tuna.tsinghua.edu.cn/deepin/"
```

客户端：

```
deb http://<apt-proxy>:3142/deepin apricot main contrib non-free
```

两个容易踩的点：

1. **兜底 `.*` 规则不能省。** 没有命中任何 cache rule 的路径返回 404 而不是透传，而 `apt update` 除了 `InRelease` 还会抓 `Packages.xz`、`by-hash/...`；少了兜底规则会在验签之后立刻失败。
2. **docker-compose 里要显式指定配置路径。** 只把文件挂到 `/etc/apt-proxy/distributions.yaml` 是不够的，示例里同时设置了环境变量：

```yaml
environment:
  - APT_PROXY_DISTRIBUTIONS_CONFIG=/etc/apt-proxy/distributions.yaml
```

启动日志会写明实际生效的文件和注册结果，可以用来确认：

```
config="/etc/apt-proxy/distributions.yaml" distributions=["alpine","centos","debian","deepin","ubuntu","ubuntu-ports"]
```

### 关于「Debian 与 Deepin 同实例是否互相覆盖」

不会。Deepin 是 `type: 6`，与内置的 Debian（`type: 3`）是不同类型，各自持有独立的 `url_pattern` 和 rewriter 状态；只有当 YAML 条目显式写 `type: 1`–`5` 时才会重新配置对应的内置发行版，这份示例没有。加载示例后实测：`/debian/...`、`/ubuntu/...` 仍分别重写到各自镜像，`/deepin/...` 走 Deepin 镜像，互不干扰。

### 需要说明的验证边界

示例带有测试，覆盖的是**路由**：四种 apt 请求形态（`InRelease`、`Packages.xz`、`by-hash/`、`.deb`）都能匹配，且不会越界去认领不属于它的路径。另有一个端到端测试验证自定义发行版的请求确实能到达其镜像。

如果你跑通了（或没跑通），欢迎回帖
