### ISSUE TITLE
Armbian镜像支持

### ISSUE THREAD

**Issue by huanghe2015** [soulteary/apt-proxy#24]
因为Armbian在使用Debian镜像源的同时会搜索Armbian自己的镜像，希望未来能加上类似的镜像支持。
```
root@onecloud:~/Downloads# http_proxy=http://localhost:3142 apt -o pkgProblemResolver=true -o Acquire::http=true update
0% [Working]2025/01/15 06:30:54 Rewrote "http://ftp.cn.debian.org/debian/dists/bullseye/InRelease" to "http://mirror.nju.edu.cn/debian/dists/bullseye/InRelease"
Ign:1 http://security.debian.org bookworm-security InRelease
Ign:2 http://apt.armbian.com bookworm InRelease
Err:3 http://apt.armbian.com bookworm Release
  404  Not Found [IP: ::1 3142]
Err:4 http://security.debian.org bookworm-security Release
  404  Not Found [IP: ::1 3142]
Ign:5 https://github.armbian.com/configng stable InRelease
0% [Waiting for headers]2025/01/15 06:30:54 [::1] "GET http://mirror.nju.edu.cn/debian/dists/bullseye/InRelease HTTP/1.1" (Not Modified) 0 SKIP 47.783259ms
Hit:6 http://ftp.cn.debian.org/debian bullseye InRelease
Ign:5 https://github.armbian.com/configng stable InRelease
Ign:5 https://github.armbian.com/configng stable InRelease
0% [Working]2025/01/15 06:30:59 Rewrote "http://deb.debian.org/debian/dists/bookworm/InRelease" to "http://mirror.nju.edu.cn/debian/dists/bookworm/InRelease"
2025/01/15 06:30:59 [::1] "GET http://mirror.nju.edu.cn/debian/dists/bookworm/InRelease HTTP/1.1" (Not Modified) 0 SKIP 32.694494ms
2025/01/15 06:30:59 Rewrote "http://deb.debian.org/debian/dists/bookworm-updates/InRelease" to "http://mirror.nju.edu.cn/debian/dists/bookworm-updates/InRelease"
Hit:7 http://deb.debian.org/debian bookworm InRelease
0% [Waiting for headers]2025/01/15 06:30:59 [::1] "GET http://mirror.nju.edu.cn/debian/dists/bookworm-updates/InRelease HTTP/1.1" (Not Modified) 0 SKIP 33.972473ms
2025/01/15 06:30:59 Rewrote "http://deb.debian.org/debian/dists/bookworm-backports/InRelease" to "http://mirror.nju.edu.cn/debian/dists/bookworm-backports/InRelease"
Hit:8 http://deb.debian.org/debian bookworm-updates InRelease
0% [Waiting for headers]2025/01/15 06:31:00 [::1] "GET http://mirror.nju.edu.cn/debian/dists/bookworm-backports/InRelease HTTP/1.1" (Not Modified) 0 SKIP 35.965443ms
Hit:9 http://deb.debian.org/debian bookworm-backports InRelease
Err:5 https://github.armbian.com/configng stable InRelease
  Invalid response from proxy: HTTP/1.1 404 Not Found  Date: Wed, 15 Jan 2025 06:30:54 GMT  Content-Length: 9  Content-Type: text/plain; charset=utf-8     [IP: ::1 3142]
Reading package lists... Done
E: The repository 'http://apt.armbian.com bookworm Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://security.debian.org bookworm-security Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by soulteary** [comment]
这个需求合理，继续作为 Armbian 发行版增强保留。

原日志中的 Debian Security 404 已由 #81–#84 解决；剩余范围应聚焦于 `apt.armbian.com` 和 `github.armbian.com/configng` 等 Armbian 自有仓库。实现需要明确仓库映射、HTTPS 处理、缓存规则、支持的 Armbian/Debian 版本，并提供 `apt update` 与包下载的端到端测试；不应通过任意上游 passthrough 实现。

**Comment by soulteary** [comment]
v0.16.0 起这个场景可以直接配置，不用改代码。

 Deepin 的仓库带路径前缀，按普通发行版配即可。在 `distributions.yaml` 里加一项，`type` 填 `1`–`5` 之外的数字（这个范围被内置发行版占用，填别的数字就是注册一个新发行版）：

 ```yaml
 distributions:
   - id: deepin
     name: Deepin
     type: 6
     url_pattern: "/deepin/(.+)$"
     benchmark_url: "dists/apricot/main/binary-amd64/Release"
     cache_rules:
       - pattern: "deb$"
         cache_control: "max-age=100000"
         rewrite: true
       - pattern: "(InRelease|Release(\\.gpg)?)$"
         cache_control: "max-age=3600"
         rewrite: true
       # 兜底规则必须放最后：apt 还会拉 Packages.xz、by-hash/... 等索引，
       # 未命中任何规则的路径会直接返回 404
       - pattern: ".*"
         cache_control: "max-age=3600"
         rewrite: true
     mirrors:
       official:
         - "community-packages.deepin.com/deepin/"
         - "mirrors.tuna.tsinghua.edu.cn/deepin/"
 ```

 客户端：

 ```text
 deb http://<apt-proxy 地址>:3142/deepin apricot main contrib non-free
 ```

 两个容易踩的坑：

 - **必须用 `--distributions-config` 指定配置文件路径**（或环境变量 `APT_PROXY_DISTRIBUTIONS_CONFIG`）。服务端不会自动探测，文件放在二进制旁边也不生效：
   ```bash
   ./apt-proxy --distributions-config=./config/distributions.yaml
   ```
 - **以 `--mode=all`（默认值）运行**。`--mode` 只接受内置发行版的名字，自定义发行版只在 `all` 模式下启用。

 `benchmark_url` 请换成你所用版本里确实存在的一个小文件（上面按 apricot 写的，Deepin 23 请改成对应 suite）。

 完整说明见 README 的[添加 apt-proxy 未内置的发行版](https://github.com/soulteary/apt-proxy/blob/main/README_CN.md#添加-apt-proxy-未内置的发行版)。抱歉这个问题搁置了这么久。
